blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/dandragona/viszi/discussions
    about: For open-ended questions, not yet-actionable bug reports.
