import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { absolutize } from '../../shared/paths.js';
import { Logger, k } from '../logger.js';

export interface InitArgs {
  path?: string;
  force?: boolean;
  withIgnore?: boolean;
  quiet?: boolean;
  verbose?: boolean;
}

const CONFIG_TEMPLATE = `// viszi config — generated by \`viszi init\`. Full reference in
// docs/01_Specs/004_Config_Spec.md. CLI flags always win over values here.
{
  // Extra glob excludes on top of viszi's ALWAYS_EXCLUDE (which already covers
  // node_modules, dist, build, .git, .viszi, etc.).
  // "exclude": ["docs/**", "examples/**"],

  // Restrict the scan to these globs. Useful for monorepos.
  // "include": ["src/**", "lib/**"],

  // Force-group files into named modules. Overrides viszi's auto-clustering
  // for the matched files. Key = module id, value = list of globs.
  // "modules": {
  //   "auth": ["src/auth/**", "src/middleware/auth.ts"],
  //   "billing": ["src/billing/**"]
  // },

  // Override the kind viszi picks for a path. Allowed kinds:
  // service | controller | database | queue | cache | ui | library |
  // cli | job | config | external | module | unknown
  // "componentKinds": {
  //   "src/db/**": "database",
  //   "src/queue/**": "queue"
  // },

  // Filter the flows the AI emits, by flow id.
  // "flows": {
  //   "include": ["login", "checkout"],
  //   "exclude": [],
  //   // Tag a flow as "mostly internal to X" when this fraction of steps share one
  //   // componentId. Default 0.8. Set > 1 to disable.
  //   "monoComponentThreshold": 0.8
  // },

  // AI tuning. CLI flags override these.
  // "ai": {
  //   "model": "sonnet",
  //   "maxBudgetUsd": 0.25,
  //   "concurrency": 6
  // }
}
`;

const IGNORE_TEMPLATE = `# .viszi-ignore — gitignore-syntax patterns viszi should skip on top of .gitignore.
# Anything matched here is invisible to the analyzer.
#
# Examples:
# fixtures/**
# generated/**
# *.snap
`;

export async function runInitCommand(args: InitArgs): Promise<number> {
  const verbosity = args.quiet ? 'quiet' : args.verbose ? 'verbose' : 'normal';
  const log = new Logger(verbosity);
  const root = absolutize(args.path ?? process.cwd());
  const configPath = resolve(root, '.viszi.json');
  const ignorePath = resolve(root, '.viszi-ignore');

  if (existsSync(configPath) && !args.force) {
    log.error(
      `${k.cyan(configPath)} already exists. Re-run with --force to overwrite.`,
    );
    return 1;
  }

  writeFileSync(configPath, CONFIG_TEMPLATE, 'utf8');
  log.success(`Wrote ${k.cyan(configPath)}`);

  if (args.withIgnore) {
    if (existsSync(ignorePath) && !args.force) {
      log.warn(`Left existing ${k.cyan(ignorePath)} alone (use --force to overwrite).`);
    } else {
      writeFileSync(ignorePath, IGNORE_TEMPLATE, 'utf8');
      log.success(`Wrote ${k.cyan(ignorePath)}`);
    }
  }

  log.info(
    `Edit ${k.cyan('.viszi.json')} to tune the analysis. Run ${k.cyan(`viszi ${args.path ?? '.'}`)} when you're ready.`,
  );
  return 0;
}
